# Generated by Django 6.1 on 2026-08-31 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('sede', 'Sede'), ('piso', 'Piso'), ('oficina', 'Oficina'), ('bodega', 'Bodega')], max_length=20)),
                ('ubicacion_padre', models.ForeignKey(blank=True, help_text='Ej. una oficina pertenece a un piso, un piso pertenece a una sede.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_ubicaciones', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
