# Generated by Django 6.1 on 2026-08-31 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ubicacion'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_fin_garantia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_mantenimiento', 'En mantenimiento'), ('dado_de_baja', 'Dado de baja'), ('extraviado', 'Extraviado')], default='activo', max_length=20)),
                ('especificaciones', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.categoria')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='proveedores.proveedor')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
