# Generated by Django 5.2.17 on 2026-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(default='', help_text='Prefijo para códigos de activo de esta categoría, ej. "LAP" genera LAP-001, LAP-002...', max_length=5),
            preserve_default=False,
        ),
    ]
