# Generated by Django 5.2.17 on 2026-09-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_categoria_prefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(help_text='Prefijo para códigos de activo de esta categoría, ej. "LAP" genera LAP-001, LAP-002...', max_length=5, unique=True),
        ),
    ]
