# Generated by Django 5.2.17 on 2026-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_categoria_prefijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='motivo_baja',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
