# Generated by Django 5.2.17 on 2026-09-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_area_ubicacion'),
        ('inventario', '0006_activo_fecha_baja_activo_motivo_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='area_creador',
            field=models.ForeignKey(blank=True, help_text='Área del usuario que creó este activo. Todos los de esa área pueden verlo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='areas.area'),
        ),
    ]
