# Generated by Django 5.2.17 on 2026-09-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventario', '0007_activo_area_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este activo. Se asigna automáticamente según la empresa del usuario que lo crea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='empresas.empresa'),
        ),
    ]
