# Generated by Django 5.2.17 on 2026-09-14 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_username', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('login', 'Inicio de sesión'), ('login_fallido', 'Inicio de sesión fallido'), ('logout', 'Cierre de sesión')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('cambios', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
