# Generated by Django 5.2.17 on 2026-09-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('inventario', '0005_alter_categoria_prefijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicación física por defecto de esta área. Se usa para actualizar automáticamente dónde está un activo al asignarlo a alguien de esta área.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='inventario.ubicacion'),
        ),
    ]
