# Generated by Django 5.2.17 on 2026-09-01 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_activo'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('entrega', 'Entrega'), ('devolucion', 'Devolución'), ('traslado', 'Traslado')], max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_entrega', to='inventario.activo')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_generadas', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_entrega', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Acta de entrega',
                'verbose_name_plural': 'Actas de entrega',
                'ordering': ['-fecha'],
            },
        ),
    ]
