# Generated by Django 5.2.17 on 2026-09-01 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
        ('custodia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaentrega',
            name='custodia',
            field=models.ForeignKey(blank=True, help_text='Custodia que originó esta acta, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_entrega', to='custodia.custodia'),
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='firma',
            field=models.TextField(blank=True, help_text='Firma capturada en pantalla, guardada como imagen en base64.'),
        ),
    ]
