# Generated by Django 5.2.17 on 2026-09-01 00:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_activo'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, help_text='Úsalo en vez de persona cuando el custodio es un área completa, no alguien específico.', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío = custodia activa actualmente.', null=True)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario')], default='principal', max_length=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodias', to='inventario.activo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Custodia',
                'verbose_name_plural': 'Custodias',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
