# Generated by Django 5.2.17 on 2026-09-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('custodia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodia',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Úsalo en vez de persona cuando el custodio es un área completa, no alguien específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodias', to='areas.area'),
        ),
    ]
