# Generated by Django 5.2.17 on 2026-09-20 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0002_alter_custodia_area'),
        ('inventario', '0005_alter_categoria_prefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodia',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='inventario.activo'),
        ),
    ]
