# Generated by Django 5.2.17 on 2026-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, help_text='Área/departamento del usuario. Determina qué datos puede ver si no es Admin.', max_length=100),
        ),
    ]
