# Generated by Django 5.2.17 on 2026-09-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('usuarios', '0002_usuario_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área/departamento del usuario. Determina qué datos puede ver si no es Admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='areas.area'),
        ),
    ]
