# Generated by Django 5.2.17 on 2026-09-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0003_alter_usuario_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece. Determina qué datos puede ver si no es Admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='empresas.empresa'),
        ),
    ]
