# Generated by Django 5.2.17 on 2026-09-20 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_categoria_prefijo'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='inventario.activo'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.activo'),
        ),
    ]
