# Generated by Django 6.1 on 2026-08-31 14:40

import proveedores.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('ruc', models.CharField(help_text='RUC ecuatoriano de 13 dígitos.', max_length=13, unique=True, validators=[proveedores.models.validar_ruc_ecuador])),
                ('contacto', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
