# Generated by Django 5.2.17 on 2026-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo_filename',
            field=models.CharField(blank=True, help_text='Nombre exacto del archivo dentro de la carpeta static/ del backend, ej. logo_empresa_a.png. Si se deja vacío, se usa el logo por defecto del sistema.', max_length=255),
        ),
    ]
