# Generated by Django 5.2.17 on 2026-09-06 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta de acceso de solo consulta vinculada a esta persona, si la tiene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_vinculada', to=settings.AUTH_USER_MODEL),
        ),
    ]
