# Generated by Django 5.2.17 on 2026-09-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('personas', '0003_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='empresas.empresa'),
        ),
    ]
